spring.application.name=api-gateway
server.port=${SERVER_PORT}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.cloud.gateway.server.webmvc.routes[0].id=book-service-api
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://book-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/books/**,/books/**,/api/reviews/**,/reviews/**

spring.cloud.gateway.server.webmvc.routes[1].id=user-service-api
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**,/users/**,/api/orders/**,/orders/**

management.endpoints.web.exposure.include=health,info

debug=false
