DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       email VARCHAR(120) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
                       restriction BOOLEAN NOT NULL DEFAULT FALSE,
                       is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(255) NOT NULL,
                       genre VARCHAR(100) NOT NULL,
                       content TEXT NOT NULL,
                       price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL,
                         book_id BIGINT NOT NULL,
                         rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
                         comment TEXT,
                         CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id),
                         CONSTRAINT fk_reviews_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             book_id BIGINT NOT NULL,
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
                             CONSTRAINT fk_order_items_book FOREIGN KEY (book_id) REFERENCES books(id)
);
