DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    restriction BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE books (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_reviews_book FOREIGN KEY (book_id) REFERENCES books(id)
);

INSERT INTO users (id, username, email, password, amount, restriction) VALUES
    (1, 'alice_reads', 'alice@example.com', 'hashed_pw_1', 150.00, FALSE),
    (2, 'bob_pages', 'bob@example.com', 'hashed_pw_2', 80.00, FALSE),
    (3, 'restricted_user', 'restricted@example.com', 'hashed_pw_3', 0.00, TRUE);

INSERT INTO books (id, title, author, genre, content, price) VALUES
    (1, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', 'A Jazz Age story.', 12.99),
    (2, '1984', 'George Orwell', 'Dystopian', 'A totalitarian future.', 11.99),
    (3, 'Clean Code', 'Robert C. Martin', 'Programming', 'Software craftsmanship.', 30.00);

INSERT INTO reviews (user_id, book_id, rating, comment) VALUES
    (1, 1, 5, 'An absolute masterpiece.'),
    (2, 1, 4, 'Great atmosphere.'),
    (2, 2, 5, 'Chilling and prophetic.');
