spring.profiles.active=${ACTIVE_PROFILE}
spring.application.name=book-service

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

clients.user-service.url=${USER_SERVICE_URL}

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.userServiceRead.maxAttempts=3
resilience4j.retry.instances.userServiceRead.waitDuration=200ms
resilience4j.retry.instances.userServiceRead.enableExponentialBackoff=true
resilience4j.retry.instances.userServiceRead.exponentialBackoffMultiplier=2

debug=false
