spring.profiles.active=${ACTIVE_PROFILE}
spring.application.name=user-service
security.jwt.secret=${JWT_SECRET}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

clients.book-service.url=${BOOK_SERVICE_URL}

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.bookService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bookService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.bookService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bookService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.bookService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.bookService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.bookReviewService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bookReviewService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.bookReviewService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bookReviewService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.bookReviewService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookReviewService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.bookReviewService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.bookServiceRead.maxAttempts=3
resilience4j.retry.instances.bookServiceRead.waitDuration=200ms
resilience4j.retry.instances.bookServiceRead.enableExponentialBackoff=true
resilience4j.retry.instances.bookServiceRead.exponentialBackoffMultiplier=2

resilience4j.retry.instances.bookReviewServiceRead.maxAttempts=3
resilience4j.retry.instances.bookReviewServiceRead.waitDuration=200ms
resilience4j.retry.instances.bookReviewServiceRead.enableExponentialBackoff=true
resilience4j.retry.instances.bookReviewServiceRead.exponentialBackoffMultiplier=2

resilience4j.retry.instances.bookReviewServiceDelete.maxAttempts=3
resilience4j.retry.instances.bookReviewServiceDelete.waitDuration=200ms
resilience4j.retry.instances.bookReviewServiceDelete.enableExponentialBackoff=true
resilience4j.retry.instances.bookReviewServiceDelete.exponentialBackoffMultiplier=2

debug=false
