spring.profiles.active=${ACTIVE_PROFILE}
spring.application.name=eureka-server
server.port=${SERVER_PORT}

logging.logstash.host=${LOGSTASH_HOST}
logging.logstash.port=${LOGSTASH_PORT}
logging.logstash.environment=${ACTIVE_PROFILE}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
