input {
  tcp {
    port => 5005
    codec => json_lines
  }
}

filter {
  if ![application] {
    mutate {
      add_field => {
        "application" => "unknown-service"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "online-bookshop-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
